name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/maps .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Docker image
      run: |
        docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/maps artjomf/maps:${{ github.sha }}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/maps:${{ github.sha }}
        docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/maps:${{ github.sha }} artjomf/maps:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/maps:latest
